global:
  api-listen-addr: :5183
  timeout: 1200s
  light-cache-size: 100

chains:
- key: cosmos
  chain-id: cosmoshub-4
  rpc-addr: http://localhost:26657
  account-prefix: cosmos
  gas-adjustment: 3
  gas-prices: 0.001uatom
  trusting-period: 336h
paths:
  cosmosm:
    src:
      chain-id: emoney-3
      client-id: 07-tendermint-7
      connection-id: connection-2
      channel-id: channel-0
      port-id: transfer
      order: UNORDERED
      version: ics20-1
    dst:
      chain-id: osmosis-1
      client-id: 07-tendermint-1447
      connection-id: connection-1132
      channel-id: channel-37
      port-id: transfer
      order: UNORDERED
      version: ics20-1
    strategy:
      type: naive
